### ISSUE TITLE
Update corobo message accordingly if a newcomer tries to assign a issue above `difficulty/low` level.

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#425]
Opened by @im-Nishant at [Gitter](https://gitter.im/coala/corobo?at=5a2038353c69dd4917097b7b)

**Comment by im-Nishant** [comment]
>A newcomer cannot be assigned to an issue with a difficulty level higher than newcomer or low difficulty.

This message should be more precise for a newcomer who haven't solved any issue and for the one who has solved only `difficulty/newcomer` issue.(go through `Labhub.py` file)

If you have any other confusion go through gitter chatlog, https://gitter.im/coala/corobo?at=5a20304dcc1d527f6bd4b3b8

**Comment by jayvdb** [comment]
I'm pretty sure we already have an issue about that.

**Comment by im-Nishant** [comment]
Actually i thought that too. Searched and got a similar existing issue https://github.com/coala/corobo/issues/328 but in gitter discussion it concluded to be different from this, so created a new one.

**Comment by RaiVaibhav** [comment]
dupe https://github.com/coala/corobo/issues/296
maintainer close this PR

**Comment by Makman2** [comment]
Tbh I think #296 is not a dupe but was already solved. This issue is about improving the message.

**Comment by jayvdb** [comment]
#296 was not solved, (has since been a huge mess), but is now re-opened, and needs to be how this is done.
Also #328 follows that, as level `medium` to do a larger overhaul.
This issue is a duplicate of #296 and #328 .
